name: redfin-etl

# when to run workflow - should happen on new pushes and once a week on saturdays
on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 0 * * 6'

jobs:
  run-notebook:
    runs-on: windows-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
      REDFIN_RAPIDAPI_KEY: ${{ secrets.REDFIN_RAPIDAPI_KEY }}
    
    steps:
      - if: ${{ env.AWS_SECRET_ACCESS_KEY != '' }}
        run: echo 'This step will only run if the secret has a value set.'

      - if: ${{ env.AWS_SECRET_ACCESS_KEY == '' }}
        run: echo 'This step will only run if the secret does not have a value set.'

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11.5
        uses: actions/setup-python@v5
        with:
          python-version: 3.11.5
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Redfin notebook
        run: jupyter execute Redfin_Analysis.ipynb